#ifndef XMLKEYWORDS_INCLUDED
#define XMLKEYWORDS_INCLUDED

#define XMLNP_MODEL     "model"
#define XMLNP_DRIFT     "drift"
#define XMLNP_SCALE     "scale"
#define XMLNP_SHIFT     "shift"
#define XMLNP_VAR       "var"
#define XMLNP_ORDER     "order"
#define XMLNP_SKIP      "skip"
#define XMLNP_DELETE    "delete"
#define XMLNP_BEGIN     "begin"
#define XMLNP_EXTEND    "extend"
#define XMLNP_STATES    "states"
#define XMLNP_STATE     "state"
#define XMLNP_KMER      "kmer"
#define XMLNP_EVENTS    "events"
#define XMLNP_TICKS     "ticks"
#define XMLNP_MEAN      "mean"
#define XMLNP_STDV      "stdv"
#define XMLNP_START     "start"
#define XMLNP_NULLMODEL "null"
#define XMLNP_FREQ      "freq"
#define XMLNP_SEQLEN    "seqlen"
#define XMLNP_PSEUDO    "pseudo"
#define XMLNP_PARAM     "param"
#define XMLNP_COUNT     "count"

#define XMLNP_COUNTS    "counts"
#define XMLNP_YES       "yes"
#define XMLNP_NO        "no"
#define XMLNP_M0        "n"
#define XMLNP_M1        "sum"
#define XMLNP_M2        "sumsq"

#endif /* XMLKEYWORDS_INCLUDED */
